### ISSUE TITLE
Link in setup.py (and PyPi) link PyPa to example project

### ISSUE THREAD

**Issue by Bartvds** [3Top/lru2cache#1]
I was browsing PyPi and found your module and I wanted to look into the sourcecode but the link in the `setup.py` still points to the repo of the template you used:

From the summary 'Homepage': https://pypi.python.org/pypi/lru2cache/0.1.0

It links this: https://github.com/pypa/sampleproject

But we're here now: https://github.com/3Top/lru2cache

Not a big deal, took me _seconds_ to Google :smile:

**Comment by mjbrams** [comment]
Thanks for the heads up.  Will fix this tomorrow when I am at a computer!  Hope you find it useful.
